apiVersion: v1
kind: Service
metadata:
  name: app-server-service
spec:
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP # Only exposes the service internally within the cluster
